version: '3'

services:

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    

  api:
    depends_on: 
      - "postgres"
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: familybudgetapi
    restart: unless-stopped
    ports:
      - 5018:5018
    

  web:  
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: familybudgetweb
    restart: unless-stopped
    ports:
      - 3000:3000  
     

volumes:
  postgres:
    driver: local

 