# build environment
FROM node:18-alpine as build
WORKDIR /app

COPY package*.json ./

ENV NODE_ENV production

RUN npm install

COPY . ./

RUN yarn run build

# expose environment
FROM bitnami/nginx:1.21.6-debian-10-r14

COPY nginx.conf /opt/bitnami/nginx/conf
COPY --from=build /app/dist/ /app/

EXPOSE 3000/tcp